### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'cov3D_precomp'

### ISSUE THREAD

**Issue by BilendM** [zeng-yifei/STAG4D#11]
Hello! Thank you for this project! I am trying to run it but I am facing an issue and I would appreciate it if you guys could help me resolve it.

I followed all the installation steps and everything was completed successfully however, when I run the `python main.py --config configs/stag4d.yaml path=dataset/minions save_path=minions` command I get the following error:
```bash
feature_dim: 128
Number of points at initialisation :  10000
[INFO] loading zero123...
/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py:1388: FutureWarning: You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.The default model files: {'clip_camera_projection/diffusion_pytorch_model.safetensors', 'image_encoder/model.safetensors', 'unet/diffusion_pytorch_model.safetensors', 'vae/diffusion_pytorch_model.safetensors'} will be loaded instead. Make sure to not load from `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error in v0.22.0 as defaulting to non-variantmodeling files is deprecated.
  deprecate("no variant default", "0.22.0", deprecation_message, standard_warn=False)
Loading pipeline components...:  50%|████████████████████████████████████                                    | 3/6 [00:00<00:00,  5.97it/s]The config attributes {'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  7.11it/s]
[INFO] loaded zero123!
  0%|                                                                                                             | 0/8001 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 1000, in <module>
    gui.train(opt.save_step+1)
  File "main.py", line 972, in train
    self.train_step()
  File "main.py", line 290, in train_step
    out = self.renderer.render(cur_cam,stage=self.stage)
  File "/home/bilend/projects/STAG4D/gs_renderer_4d.py", line 888, in render
    rendered_image, rendered_depth, rendered_alpha, radii = rasterizer(
  File "/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'cov3D_precomp'
```
The cloned repo already had the /minions folder in the /dataset folder so I did not modify that.

Below is my system and environment details:
- Python: `3.8.19`
- Torchvision: `cu121` Although this was not listed in the requirements.txt, but the project would not run without it.

nvidia-smi:
```bash
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.52.01              Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2070        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              5W /   30W |       0MiB /   8192MiB |      0%      Default |
```
nvcc --version:
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

Your help would be much appreciated! Thank you :)

**Comment by zeng-yifei** [comment]
Can you check if you are using the `diff_gauss` from `https://github.com/slothfulxtx/diff-gaussian-rasterization.git` as the rasterizer lib? Most problem of this line comes from using the different version of gaussian rasterizer.

**Comment by zmf2022** [comment]
Hi,
we rename the cov3D_precomp as cov3Ds_precomp, following the naming rules of other arguments in the function. You can just ignore this argument during function call because we need scales and rotations to compute normal maps.

**Comment by zmf2022** [comment]
you should change code as follows

 # Rasterize visible Gaussians to image, obtain their radii (on screen).
        rendered_image, rendered_depth, rendered_norm, rendered_alpha, radii, rendered_extra = rasterizer(
        means3D = means3D_final,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity_final,
        scales = scales_final,
        rotations = rotations_final,
        cov3Ds_precomp = cov3Ds_precomp)

**Comment by BilendM** [comment]
> Can you check if you are using the `diff_gauss` from `https://github.com/slothfulxtx/diff-gaussian-rasterization.git` as the rasterizer lib? Most problem of this line comes from using the different version of gaussian rasterizer.

I double-checked this and yes, I am using the `diff-gaus` from the provided repo

**Comment by BilendM** [comment]
> you should change code as follows
> 
> # Rasterize visible Gaussians to image, obtain their radii (on screen).
> ```
>     rendered_image, rendered_depth, rendered_norm, rendered_alpha, radii, rendered_extra = rasterizer(
>     means3D = means3D_final,
>     means2D = means2D,
>     shs = shs,
>     colors_precomp = colors_precomp,
>     opacities = opacity_final,
>     scales = scales_final,
>     rotations = rotations_final,
>     cov3Ds_precomp = cov3Ds_precomp)
> ```

This seems to be working! 
```
feature_dim: 128
Number of points at initialisation :  10000
[INFO] loading zero123...
/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/bilend/miniconda3/envs/stag4d/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py:1388: FutureWarning: You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.The default model files: {'image_encoder/model.safetensors', 'unet/diffusion_pytorch_model.safetensors', 'clip_camera_projection/diffusion_pytorch_model.safetensors', 'vae/diffusion_pytorch_model.safetensors'} will be loaded instead. Make sure to not load from `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error in v0.22.0 as defaulting to non-variantmodeling files is deprecated.
  deprecate("no variant default", "0.22.0", deprecation_message, standard_warn=False)
Loading pipeline components...:   0%|                                                                                              | 0/6 [00:00<?, ?it/s]The config attributes {'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  8.79it/s]
[INFO] loaded zero123!
  2%|█▊                                                                                                             | 127/8001 [01:30<1:35:41,  1.37it/s]
```

Thank you so much!

**Comment by zeng-yifei** [comment]
Sorry that I didn't notice the updated version of diff_gauss. The return format of the rasterization is changed at that time. Now I have fixed the bug. Thank you all for your discussions!
